#!/bin/bash

# This hook prepares "Heroku Git" deployment method 
# for using by Heroku CLI (Heroku CLI must be installed).

url="$2"

if [[ $url =~ heroku ]] ; then
	echo ------------------------
	echo git heroku pre-push hook
	echo ------------------------
	
	# Setting Heroku's stack to "heroku-20" makes available 
	# Heroku Git deployment
	echo Step 1. Setting Heroku stack:
	heroku stack:set heroku-20

	# Setting config variable makes available 
	# to use Git hash value in Heroku runtime mode
	echo Step 2. Setting Heroku config variables:
	heroku config:set SOURCE_HASH=$(git rev-parse HEAD)
	heroku config:set SOURCE_NAME=mg
	
	echo ------------------------
fi

exit 0