#!/bin/bash

# This hook is for "Heroku Git" deployment method 
# by using Heroku CLI (Heroku CLI must be installed).

url="$2"

if [[ $url =~ heroku ]] ; then
	echo ------------------------
	echo git heroku pre-push hook
	echo ------------------------
	
	# Setting Heroku's stack to "heroku-20" makes available 
	# Heroku Git deployment
	echo Setting heroku stack to heroku-20
	heroku stack:set heroku-20
	
	# Setting config variable makes available 
	# to use Git hash value in Heroku runtime mode
	hash_variable=SOURCE_HASH
	hash_value=$(git rev-parse HEAD)
	echo Setting $hash_variable to $hash_value
	heroku config:set $hash_variable=$hash_value
	
	echo ------------------------
fi

exit 0