name: e2e-tests
on:
  push:
    branches:
      - master
      - develop
      - "*--CI"

jobs:
  cypress-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      TMDB_API_ACCESS_TOKEN: ${{ secrets.WORKFLOW_TMDB_API_ACCESS_TOKEN }}
      TMDB_API_KEY: ${{ secrets.WORKFLOW_TMDB_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          command: npm test
