name: e2e-tests
on: [push]
jobs:
  e2e-cypress-windows-chrome:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          command: npm test
